#!/usr/bin/python
import os, sys

# Directory containing the config.py
sys.path.insert(0, os.environ['OPENSHIFT_REPO_DIR'])

virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

import Pyblosxom.pyblosxom
application = Pyblosxom.pyblosxom.PyBlosxomWSGIApp()

#
# Below for testing only
#
if __name__ == '__main__':
    from wsgiref.simple_server import make_server
    httpd = make_server('localhost', 8051, application)
    # Wait for a single request, serve it and quit.
    httpd.handle_request()
